### ISSUE TITLE
Fuel System

### ISSUE THREAD

**Issue by Caveman94** [NorthStation14/NorthStation14#18]

**Comment by sgtdestruction** [comment]
This specific thing is crossover from when we started with the aurora fork of SS13. So this may already be in the game, I haven't played enough to know.

Basically just want a way for shuttles to measure fuel.

I'm aware that frontier station has something like this.

**Comment by Caveman94** [comment]
Ah, yeah any of the power generators have a fuel input and the UI will say how much fuel is left and estimated run time

**Comment by sgtdestruction** [comment]
Cool I'm closing this
